In [48]:
import pandas as pd
import numpy as np
import os

# First, we're giong to check all the zip files for data errors

In [49]:

for filename in os.listdir('zipped'):
    if filename.endswith(".zip"):
        file_path=os.path.join("zipped",filename)
        print(f"File: {file_path}")
        df=pd.read_csv(file_path,compression="zip")
        df=df.rename(str.lower, axis='columns')
        df.info()
        
df.columns

File: zipped/JC-201811-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24910 entries, 0 to 24909
Data columns (total 15 columns):
tripduration               24910 non-null int64
starttime                  24910 non-null object
stoptime                   24910 non-null object
start station id           24910 non-null int64
start station name         24910 non-null object
start station latitude     24910 non-null float64
start station longitude    24910 non-null float64
end station id             24910 non-null int64
end station name           24910 non-null object
end station latitude       24910 non-null float64
end station longitude      24910 non-null float64
bikeid                     24910 non-null int64
usertype                   24910 non-null object
birth year                 24910 non-null int64
gender                     24910 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 2.9+ MB
File: zipped/JC-201804-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23634 entries, 0 to 23633
Data columns (total 15 columns):
tripduration               23634 non-null int64
starttime                  23634 non-null object
stoptime                   23634 non-null object
start station id           23634 non-null int64
start station name         23634 non-null object
start station latitude     23634 non-null float64
start station longitude    23634 non-null float64
end station id             23634 non-null int64
end station name           23634 non-null object
end station latitude       23634 non-null float64
end station longitude      23634 non-null float64
bikeid                     23634 non-null int64
usertype                   23634 non-null object
birth year                 23634 non-null int64
gender                     23634 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 2.7+ MB
File: zipped/JC-201803-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17109 entries, 0 to 17108
Data columns (total 15 columns):
tripduration               17109 non-null int64
starttime                  17109 non-null object
stoptime                   17109 non-null object
start station id           17109 non-null int64
start station name         17109 non-null object
start station latitude     17109 non-null float64
start station longitude    17109 non-null float64
end station id             17109 non-null int64
end station name           17109 non-null object
end station latitude       17109 non-null float64
end station longitude      17109 non-null float64
bikeid                     17109 non-null int64
usertype                   17109 non-null object
birth year                 17109 non-null int64
gender                     17109 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 2.0+ MB
File: zipped/JC-201704-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21186 entries, 0 to 21185
Data columns (total 15 columns):
tripduration               21186 non-null int64
starttime                  21186 non-null object
stoptime                   21186 non-null object
start station id           21186 non-null int64
start station name         21186 non-null object
start station latitude     21186 non-null float64
start station longitude    21186 non-null float64
end station id             21186 non-null int64
end station name           21186 non-null object
end station latitude       21186 non-null float64
end station longitude      21186 non-null float64
bikeid                     21186 non-null int64
usertype                   21186 non-null object
birth year                 19213 non-null float64
gender                     21186 non-null int64
dtypes: float64(5), int64(5), object(5)
memory usage: 2.4+ MB
File: zipped/JC-201901-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19676 entries, 0 to 19675
Data columns (total 15 columns):
tripduration               19676 non-null int64
starttime                  19676 non-null object
stoptime                   19676 non-null object
start station id           19676 non-null int64
start station name         19676 non-null object
start station latitude     19676 non-null float64
start station longitude    19676 non-null float64
end station id             19676 non-null int64
end station name           19676 non-null object
end station latitude       19676 non-null float64
end station longitude      19676 non-null float64
bikeid                     19676 non-null int64
usertype                   19676 non-null object
birth year                 19676 non-null int64
gender                     19676 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 2.3+ MB
File: zipped/JC-201711-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23582 entries, 0 to 23581
Data columns (total 15 columns):
tripduration               23582 non-null int64
starttime                  23582 non-null object
stoptime                   23582 non-null object
start station id           23582 non-null int64
start station name         23582 non-null object
start station latitude     23582 non-null float64
start station longitude    23582 non-null float64
end station id             23582 non-null int64
end station name           23582 non-null object
end station latitude       23582 non-null float64
end station longitude      23582 non-null float64
bikeid                     23582 non-null int64
usertype                   23582 non-null object
birth year                 22735 non-null float64
gender                     23582 non-null int64
dtypes: float64(5), int64(5), object(5)
memory usage: 2.7+ MB
File: zipped/JC-201904-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33056 entries, 0 to 33055
Data columns (total 15 columns):
tripduration               33056 non-null int64
starttime                  33056 non-null object
stoptime                   33056 non-null object
start station id           33056 non-null int64
start station name         33056 non-null object
start station latitude     33056 non-null float64
start station longitude    33056 non-null float64
end station id             33056 non-null int64
end station name           33056 non-null object
end station latitude       33056 non-null float64
end station longitude      33056 non-null float64
bikeid                     33056 non-null int64
usertype                   33056 non-null object
birth year                 33056 non-null int64
gender                     33056 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 3.8+ MB
File: zipped/JC-201709-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33119 entries, 0 to 33118
Data columns (total 15 columns):
tripduration               33119 non-null int64
starttime                  33119 non-null object
stoptime                   33119 non-null object
start station id           33119 non-null int64
start station name         33119 non-null object
start station latitude     33119 non-null float64
start station longitude    33119 non-null float64
end station id             33119 non-null int64
end station name           33119 non-null object
end station latitude       33119 non-null float64
end station longitude      33119 non-null float64
bikeid                     33119 non-null int64
usertype                   33119 non-null object
birth year                 30735 non-null float64
gender                     33119 non-null int64
dtypes: float64(5), int64(5), object(5)
memory usage: 3.8+ MB
File: zipped/JC-201806-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40937 entries, 0 to 40936
Data columns (total 15 columns):
tripduration               40937 non-null int64
starttime                  40937 non-null object
stoptime                   40937 non-null object
start station id           40937 non-null int64
start station name         40937 non-null object
start station latitude     40937 non-null float64
start station longitude    40937 non-null float64
end station id             40937 non-null int64
end station name           40937 non-null object
end station latitude       40937 non-null float64
end station longitude      40937 non-null float64
bikeid                     40937 non-null int64
usertype                   40937 non-null object
birth year                 40937 non-null int64
gender                     40937 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 4.7+ MB
File: zipped/JC-201801-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12677 entries, 0 to 12676
Data columns (total 15 columns):
tripduration               12677 non-null int64
starttime                  12677 non-null object
stoptime                   12677 non-null object
start station id           12677 non-null int64
start station name         12677 non-null object
start station latitude     12677 non-null float64
start station longitude    12677 non-null float64
end station id             12677 non-null int64
end station name           12677 non-null object
end station latitude       12677 non-null float64
end station longitude      12677 non-null float64
bikeid                     12677 non-null int64
usertype                   12677 non-null object
birth year                 12677 non-null int64
gender                     12677 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 1.5+ MB
File: zipped/JC-201706-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32060 entries, 0 to 32059
Data columns (total 15 columns):
tripduration               32060 non-null int64
starttime                  32060 non-null object
stoptime                   32060 non-null object
start station id           32060 non-null int64
start station name         32060 non-null object
start station latitude     32060 non-null float64
start station longitude    32060 non-null float64
end station id             32060 non-null int64
end station name           32060 non-null object
end station latitude       32060 non-null float64
end station longitude      32060 non-null float64
bikeid                     32060 non-null int64
usertype                   32060 non-null object
birth year                 29534 non-null float64
gender                     32060 non-null int64
dtypes: float64(5), int64(5), object(5)
memory usage: 3.7+ MB
File: zipped/JC-201809-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39022 entries, 0 to 39021
Data columns (total 15 columns):
tripduration               39022 non-null int64
starttime                  39022 non-null object
stoptime                   39022 non-null object
start station id           39022 non-null int64
start station name         39022 non-null object
start station latitude     39022 non-null float64
start station longitude    39022 non-null float64
end station id             39022 non-null int64
end station name           39022 non-null object
end station latitude       39022 non-null float64
end station longitude      39022 non-null float64
bikeid                     39022 non-null int64
usertype                   39022 non-null object
birth year                 39022 non-null int64
gender                     39022 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 4.5+ MB
File: zipped/JC-201903-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23606 entries, 0 to 23605
Data columns (total 15 columns):
tripduration               23606 non-null int64
starttime                  23606 non-null object
stoptime                   23606 non-null object
start station id           23606 non-null int64
start station name         23606 non-null object
start station latitude     23606 non-null float64
start station longitude    23606 non-null float64
end station id             23606 non-null int64
end station name           23606 non-null object
end station latitude       23606 non-null float64
end station longitude      23606 non-null float64
bikeid                     23606 non-null int64
usertype                   23606 non-null object
birth year                 23606 non-null int64
gender                     23606 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 2.7+ MB
File: zipped/JC-201712-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15898 entries, 0 to 15897
Data columns (total 15 columns):
tripduration               15898 non-null int64
starttime                  15898 non-null object
stoptime                   15898 non-null object
start station id           15898 non-null int64
start station name         15898 non-null object
start station latitude     15898 non-null float64
start station longitude    15898 non-null float64
end station id             15898 non-null int64
end station name           15898 non-null object
end station latitude       15898 non-null float64
end station longitude      15898 non-null float64
bikeid                     15898 non-null int64
usertype                   15898 non-null object
birth year                 15448 non-null float64
gender                     15898 non-null int64
dtypes: float64(5), int64(5), object(5)
memory usage: 1.8+ MB
File: zipped/JC-201902-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18565 entries, 0 to 18564
Data columns (total 15 columns):
tripduration               18565 non-null int64
starttime                  18565 non-null object
stoptime                   18565 non-null object
start station id           18565 non-null int64
start station name         18565 non-null object
start station latitude     18565 non-null float64
start station longitude    18565 non-null float64
end station id             18565 non-null int64
end station name           18565 non-null object
end station latitude       18565 non-null float64
end station longitude      18565 non-null float64
bikeid                     18565 non-null int64
usertype                   18565 non-null object
birth year                 18565 non-null int64
gender                     18565 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 2.1+ MB
File: zipped/JC-201808-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44432 entries, 0 to 44431
Data columns (total 15 columns):
tripduration               44432 non-null int64
starttime                  44432 non-null object
stoptime                   44432 non-null object
start station id           44432 non-null int64
start station name         44432 non-null object
start station latitude     44432 non-null float64
start station longitude    44432 non-null float64
end station id             44432 non-null int64
end station name           44432 non-null object
end station latitude       44432 non-null float64
end station longitude      44432 non-null float64
bikeid                     44432 non-null int64
usertype                   44432 non-null object
birth year                 44432 non-null int64
gender                     44432 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 5.1+ MB
File: zipped/JC-201707-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33573 entries, 0 to 33572
Data columns (total 15 columns):
tripduration               33573 non-null int64
starttime                  33573 non-null object
stoptime                   33573 non-null object
start station id           33573 non-null int64
start station name         33573 non-null object
start station latitude     33573 non-null float64
start station longitude    33573 non-null float64
end station id             33573 non-null int64
end station name           33573 non-null object
end station latitude       33573 non-null float64
end station longitude      33573 non-null float64
bikeid                     33573 non-null int64
usertype                   33573 non-null object
birth year                 30613 non-null float64
gender                     33573 non-null int64
dtypes: float64(5), int64(5), object(5)
memory usage: 3.8+ MB
File: zipped/JC-201807-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42268 entries, 0 to 42267
Data columns (total 15 columns):
tripduration               42268 non-null int64
starttime                  42268 non-null object
stoptime                   42268 non-null object
start station id           42268 non-null int64
start station name         42268 non-null object
start station latitude     42268 non-null float64
start station longitude    42268 non-null float64
end station id             42268 non-null int64
end station name           42268 non-null object
end station latitude       42268 non-null float64
end station longitude      42268 non-null float64
bikeid                     42268 non-null int64
usertype                   42268 non-null object
birth year                 42268 non-null int64
gender                     42268 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 4.8+ MB
File: zipped/JC-201905-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36135 entries, 0 to 36134
Data columns (total 15 columns):
tripduration               36135 non-null int64
starttime                  36135 non-null object
stoptime                   36135 non-null object
start station id           36135 non-null int64
start station name         36135 non-null object
start station latitude     36135 non-null float64
start station longitude    36135 non-null float64
end station id             36135 non-null int64
end station name           36135 non-null object
end station latitude       36135 non-null float64
end station longitude      36135 non-null float64
bikeid                     36135 non-null int64
usertype                   36135 non-null object
birth year                 36135 non-null int64
gender                     36135 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 4.1+ MB
File: zipped/JC-201812-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20205 entries, 0 to 20204
Data columns (total 15 columns):
tripduration               20205 non-null int64
starttime                  20205 non-null object
stoptime                   20205 non-null object
start station id           20205 non-null int64
start station name         20205 non-null object
start station latitude     20205 non-null float64
start station longitude    20205 non-null float64
end station id             20205 non-null int64
end station name           20205 non-null object
end station latitude       20205 non-null float64
end station longitude      20205 non-null float64
bikeid                     20205 non-null int64
usertype                   20205 non-null object
birth year                 20205 non-null int64
gender                     20205 non-null int64
dtypes: float64(4), int64(6), object(5)
memory usage: 2.3+ MB
File: zipped/JC-201710-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34919 entries, 0 to 34918
Data columns (total 15 columns):
tripduration               34919 non-null int64
starttime                  34919 non-null object
stoptime                   34919 non-null object
start station id           34919 non-null int64
start station name         34919 non-null object
start station latitude     34919 non-null float64
start station longitude    34919 non-null float64
end station id             34919 non-null int64
end station name           34919 non-null object
end station latitude       34919 non-null float64
end station longitude      34919 non-null float64
bikeid                     34919 non-null int64
usertype                   34919 non-null object
birth year                 32761 non-null float64
gender                     34919 non-null int64

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

# Now, we're going to merge them and make one combined_bike_data.csv

In [51]:
combined=pd.DataFrame(columns=['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'])


for filename in os.listdir('zipped'):
    if filename.endswith(".zip"):
        file_path=os.path.join("zipped",filename)
        print(f"File: {file_path}")
        df=pd.read_csv(file_path,compression="zip")
        df=df.rename(str.lower, axis='columns')
        combined=combined.append(df,ignore_index=True)
        combined.info()

File: zipped/JC-201811-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24910 entries, 0 to 24909
Data columns (total 15 columns):
tripduration               24910 non-null object
starttime                  24910 non-null object
stoptime                   24910 non-null object
start station id           24910 non-null object
start station name         24910 non-null object
start station latitude     24910 non-null float64
start station longitude    24910 non-null float64
end station id             24910 non-null object
end station name           24910 non-null object
end station latitude       24910 non-null float64
end station longitude      24910 non-null float64
bikeid                     24910 non-null object
usertype                   24910 non-null object
birth year                 24910 non-null object
gender                     24910 non-null object
dtypes: float64(4), object(11)
memory usage: 2.9+ MB
File: zipped/JC-201804-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48544 entries, 0 to 48543
Data columns (total 15 columns):
tripduration               48544 non-null object
starttime                  48544 non-null object
stoptime                   48544 non-null object
start station id           48544 non-null object
start station name         48544 non-null object
start station latitude     48544 non-null float64
start station longitude    48544 non-null float64
end station id             48544 non-null object
end station name           48544 non-null object
end station latitude       48544 non-null float64
end station longitude      48544 non-null float64
bikeid                     48544 non-null object
usertype                   48544 non-null object
birth year                 48544 non-null object
gender                     48544 non-null object
dtypes: float64(4), object(11)
memory usage: 5.6+ MB
File: zipped/JC-201803-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65653 entries, 0 to 65652
Data columns (total 15 columns):
tripduration               65653 non-null object
starttime                  65653 non-null object
stoptime                   65653 non-null object
start station id           65653 non-null object
start station name         65653 non-null object
start station latitude     65653 non-null float64
start station longitude    65653 non-null float64
end station id             65653 non-null object
end station name           65653 non-null object
end station latitude       65653 non-null float64
end station longitude      65653 non-null float64
bikeid                     65653 non-null object
usertype                   65653 non-null object
birth year                 65653 non-null object
gender                     65653 non-null object
dtypes: float64(4), object(11)
memory usage: 7.5+ MB
File: zipped/JC-201704-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86839 entries, 0 to 86838
Data columns (total 15 columns):
tripduration               86839 non-null object
starttime                  86839 non-null object
stoptime                   86839 non-null object
start station id           86839 non-null object
start station name         86839 non-null object
start station latitude     86839 non-null float64
start station longitude    86839 non-null float64
end station id             86839 non-null object
end station name           86839 non-null object
end station latitude       86839 non-null float64
end station longitude      86839 non-null float64
bikeid                     86839 non-null object
usertype                   86839 non-null object
birth year                 84866 non-null object
gender                     86839 non-null object
dtypes: float64(4), object(11)
memory usage: 9.9+ MB
File: zipped/JC-201901-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106515 entries, 0 to 106514
Data columns (total 15 columns):
tripduration               106515 non-null object
starttime                  106515 non-null object
stoptime                   106515 non-null object
start station id           106515 non-null object
start station name         106515 non-null object
start station latitude     106515 non-null float64
start station longitude    106515 non-null float64
end station id             106515 non-null object
end station name           106515 non-null object
end station latitude       106515 non-null float64
end station longitude      106515 non-null float64
bikeid                     106515 non-null object
usertype                   106515 non-null object
birth year                 104542 non-null object
gender                     106515 non-null object
dtypes: float64(4), object(11)
memory usage: 12.2+ MB
File: zipped/JC-201711-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130097 entries, 0 to 130096
Data columns (total 15 columns):
tripduration               130097 non-null object
starttime                  130097 non-null object
stoptime                   130097 non-null object
start station id           130097 non-null object
start station name         130097 non-null object
start station latitude     130097 non-null float64
start station longitude    130097 non-null float64
end station id             130097 non-null object
end station name           130097 non-null object
end station latitude       130097 non-null float64
end station longitude      130097 non-null float64
bikeid                     130097 non-null object
usertype                   130097 non-null object
birth year                 127277 non-null object
gender                     130097 non-null object
dtypes: float64(4), object(11)
memory usage: 14.9+ MB
File: zipped/JC-201904-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163153 entries, 0 to 163152
Data columns (total 15 columns):
tripduration               163153 non-null object
starttime                  163153 non-null object
stoptime                   163153 non-null object
start station id           163153 non-null object
start station name         163153 non-null object
start station latitude     163153 non-null float64
start station longitude    163153 non-null float64
end station id             163153 non-null object
end station name           163153 non-null object
end station latitude       163153 non-null float64
end station longitude      163153 non-null float64
bikeid                     163153 non-null object
usertype                   163153 non-null object
birth year                 160333 non-null object
gender                     163153 non-null object
dtypes: float64(4), object(11)
memory usage: 18.7+ MB
File: zipped/JC-201709-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196272 entries, 0 to 196271
Data columns (total 15 columns):
tripduration               196272 non-null object
starttime                  196272 non-null object
stoptime                   196272 non-null object
start station id           196272 non-null object
start station name         196272 non-null object
start station latitude     196272 non-null float64
start station longitude    196272 non-null float64
end station id             196272 non-null object
end station name           196272 non-null object
end station latitude       196272 non-null float64
end station longitude      196272 non-null float64
bikeid                     196272 non-null object
usertype                   196272 non-null object
birth year                 191068 non-null object
gender                     196272 non-null object
dtypes: float64(4), object(11)
memory usage: 22.5+ MB
File: zipped/JC-201806-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237209 entries, 0 to 237208
Data columns (total 15 columns):
tripduration               237209 non-null object
starttime                  237209 non-null object
stoptime                   237209 non-null object
start station id           237209 non-null object
start station name         237209 non-null object
start station latitude     237209 non-null float64
start station longitude    237209 non-null float64
end station id             237209 non-null object
end station name           237209 non-null object
end station latitude       237209 non-null float64
end station longitude      237209 non-null float64
bikeid                     237209 non-null object
usertype                   237209 non-null object
birth year                 232005 non-null object
gender                     237209 non-null object
dtypes: float64(4), object(11)
memory usage: 27.1+ MB
File: zipped/JC-201801-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249886 entries, 0 to 249885
Data columns (total 15 columns):
tripduration               249886 non-null object
starttime                  249886 non-null object
stoptime                   249886 non-null object
start station id           249886 non-null object
start station name         249886 non-null object
start station latitude     249886 non-null float64
start station longitude    249886 non-null float64
end station id             249886 non-null object
end station name           249886 non-null object
end station latitude       249886 non-null float64
end station longitude      249886 non-null float64
bikeid                     249886 non-null object
usertype                   249886 non-null object
birth year                 244682 non-null object
gender                     249886 non-null object
dtypes: float64(4), object(11)
memory usage: 28.6+ MB
File: zipped/JC-201706-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281946 entries, 0 to 281945
Data columns (total 15 columns):
tripduration               281946 non-null object
starttime                  281946 non-null object
stoptime                   281946 non-null object
start station id           281946 non-null object
start station name         281946 non-null object
start station latitude     281946 non-null float64
start station longitude    281946 non-null float64
end station id             281946 non-null object
end station name           281946 non-null object
end station latitude       281946 non-null float64
end station longitude      281946 non-null float64
bikeid                     281946 non-null object
usertype                   281946 non-null object
birth year                 274216 non-null object
gender                     281946 non-null object
dtypes: float64(4), object(11)
memory usage: 32.3+ MB
File: zipped/JC-201809-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320968 entries, 0 to 320967
Data columns (total 15 columns):
tripduration               320968 non-null object
starttime                  320968 non-null object
stoptime                   320968 non-null object
start station id           320968 non-null object
start station name         320968 non-null object
start station latitude     320968 non-null float64
start station longitude    320968 non-null float64
end station id             320968 non-null object
end station name           320968 non-null object
end station latitude       320968 non-null float64
end station longitude      320968 non-null float64
bikeid                     320968 non-null object
usertype                   320968 non-null object
birth year                 313238 non-null object
gender                     320968 non-null object
dtypes: float64(4), object(11)
memory usage: 36.7+ MB
File: zipped/JC-201903-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344574 entries, 0 to 344573
Data columns (total 15 columns):
tripduration               344574 non-null object
starttime                  344574 non-null object
stoptime                   344574 non-null object
start station id           344574 non-null object
start station name         344574 non-null object
start station latitude     344574 non-null float64
start station longitude    344574 non-null float64
end station id             344574 non-null object
end station name           344574 non-null object
end station latitude       344574 non-null float64
end station longitude      344574 non-null float64
bikeid                     344574 non-null object
usertype                   344574 non-null object
birth year                 336844 non-null object
gender                     344574 non-null object
dtypes: float64(4), object(11)
memory usage: 39.4+ MB
File: zipped/JC-201712-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360472 entries, 0 to 360471
Data columns (total 15 columns):
tripduration               360472 non-null object
starttime                  360472 non-null object
stoptime                   360472 non-null object
start station id           360472 non-null object
start station name         360472 non-null object
start station latitude     360472 non-null float64
start station longitude    360472 non-null float64
end station id             360472 non-null object
end station name           360472 non-null object
end station latitude       360472 non-null float64
end station longitude      360472 non-null float64
bikeid                     360472 non-null object
usertype                   360472 non-null object
birth year                 352292 non-null object
gender                     360472 non-null object
dtypes: float64(4), object(11)
memory usage: 41.3+ MB
File: zipped/JC-201902-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379037 entries, 0 to 379036
Data columns (total 15 columns):
tripduration               379037 non-null object
starttime                  379037 non-null object
stoptime                   379037 non-null object
start station id           379037 non-null object
start station name         379037 non-null object
start station latitude     379037 non-null float64
start station longitude    379037 non-null float64
end station id             379037 non-null object
end station name           379037 non-null object
end station latitude       379037 non-null float64
end station longitude      379037 non-null float64
bikeid                     379037 non-null object
usertype                   379037 non-null object
birth year                 370857 non-null object
gender                     379037 non-null object
dtypes: float64(4), object(11)
memory usage: 43.4+ MB
File: zipped/JC-201808-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423469 entries, 0 to 423468
Data columns (total 15 columns):
tripduration               423469 non-null object
starttime                  423469 non-null object
stoptime                   423469 non-null object
start station id           423469 non-null object
start station name         423469 non-null object
start station latitude     423469 non-null float64
start station longitude    423469 non-null float64
end station id             423469 non-null object
end station name           423469 non-null object
end station latitude       423469 non-null float64
end station longitude      423469 non-null float64
bikeid                     423469 non-null object
usertype                   423469 non-null object
birth year                 415289 non-null object
gender                     423469 non-null object
dtypes: float64(4), object(11)
memory usage: 48.5+ MB
File: zipped/JC-201707-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457042 entries, 0 to 457041
Data columns (total 15 columns):
tripduration               457042 non-null object
starttime                  457042 non-null object
stoptime                   457042 non-null object
start station id           457042 non-null object
start station name         457042 non-null object
start station latitude     457042 non-null float64
start station longitude    457042 non-null float64
end station id             457042 non-null object
end station name           457042 non-null object
end station latitude       457042 non-null float64
end station longitude      457042 non-null float64
bikeid                     457042 non-null object
usertype                   457042 non-null object
birth year                 445902 non-null object
gender                     457042 non-null object
dtypes: float64(4), object(11)
memory usage: 52.3+ MB
File: zipped/JC-201807-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499310 entries, 0 to 499309
Data columns (total 15 columns):
tripduration               499310 non-null object
starttime                  499310 non-null object
stoptime                   499310 non-null object
start station id           499310 non-null object
start station name         499310 non-null object
start station latitude     499310 non-null float64
start station longitude    499310 non-null float64
end station id             499310 non-null object
end station name           499310 non-null object
end station latitude       499310 non-null float64
end station longitude      499310 non-null float64
bikeid                     499310 non-null object
usertype                   499310 non-null object
birth year                 488170 non-null object
gender                     499310 non-null object
dtypes: float64(4), object(11)
memory usage: 57.1+ MB
File: zipped/JC-201905-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 535445 entries, 0 to 535444
Data columns (total 15 columns):
tripduration               535445 non-null object
starttime                  535445 non-null object
stoptime                   535445 non-null object
start station id           535445 non-null object
start station name         535445 non-null object
start station latitude     535445 non-null float64
start station longitude    535445 non-null float64
end station id             535445 non-null object
end station name           535445 non-null object
end station latitude       535445 non-null float64
end station longitude      535445 non-null float64
bikeid                     535445 non-null object
usertype                   535445 non-null object
birth year                 524305 non-null object
gender                     535445 non-null object
dtypes: float64(4), object(11)
memory usage: 61.3+ MB
File: zipped/JC-201812-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555650 entries, 0 to 555649
Data columns (total 15 columns):
tripduration               555650 non-null object
starttime                  555650 non-null object
stoptime                   555650 non-null object
start station id           555650 non-null object
start station name         555650 non-null object
start station latitude     555650 non-null float64
start station longitude    555650 non-null float64
end station id             555650 non-null object
end station name           555650 non-null object
end station latitude       555650 non-null float64
end station longitude      555650 non-null float64
bikeid                     555650 non-null object
usertype                   555650 non-null object
birth year                 544510 non-null object
gender                     555650 non-null object
dtypes: float64(4), object(11)
memory usage: 63.6+ MB
File: zipped/JC-201710-citibike-tripdata.csv.zip
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590569 entries, 0 to 590568
Data columns (total 15 columns):
tripduration               590569 non-null object
starttime                  590569 non-null object
stoptime                   590569 non-null object
start station id           590569 non-null object
start station name         590569 non-null object
start station latitude     590569 non-null float64
start station longitude    590569 non-null float64
end station id             590569 non-null object
end station name           590569 non-null object
end station latitude       590569 non-null float64

In [52]:
combined.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1188,2018-11-01 06:32:27.5190,2018-11-01 06:52:15.9140,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,33662,Customer,1969,0
1,278,2018-11-01 07:14:31.8680,2018-11-01 07:19:10.2610,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29254,Subscriber,1963,1
2,115,2018-11-01 07:33:17.1920,2018-11-01 07:35:12.2830,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,33607,Subscriber,1966,1
3,155,2018-11-01 08:20:10.9320,2018-11-01 08:22:46.7050,3183,Exchange Place,40.716247,-74.033459,3681,Grand St,40.715178,-74.037683,29222,Subscriber,1975,2
4,82,2018-11-01 08:35:02.7850,2018-11-01 08:36:25.1840,3183,Exchange Place,40.716247,-74.033459,3184,Paulus Hook,40.714145,-74.033552,29678,Subscriber,1975,1

In [53]:
combined.to_csv("combined_bike_data.csv")